### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [francoisfds/BikeSharingHub#10]
Everything in https://hosted.weblate.org/projects/bikesharinghub/#information
is now AGPLv1+, whereas https://github.com/francoisfds/BikeSharingHub/blob/master/LICENSE says GPLv3

I think it should be GPLv3+, or ideally AGPLv3+ for both.

It can be changed in
https://hosted.weblate.org/settings/bikesharinghub/bikesharinghub/
and
https://hosted.weblate.org/settings/bikesharinghub/glossary/

**Comment by comradekingu** [comment]
Top stuff. GPLv3+ for both now.

**Comment by Altonss** [comment]
This isn't an official repo, just some testing from me for now...
