### ISSUE TITLE
improvments for selecting area/service

### ISSUE THREAD

**Issue by DJCrashdummy** [francoisfds/BikeSharingHub#2]
since OpenBikeSharing seems abandoned (https://github.com/bparmentier/OpenBikeSharing/issues/58), i'm opening here my tickets with ideas for improvement:

since the list for choosing your city/area/provider/service is just ordered by alphabet there is room for improvement IMHO... in my country a bunch of services are not named after the city but after a wider area *(and it can be sometimes tricky to figure out its name because they are not really "official")*, or the provider named it's service after a small village which started at first in the area and then expanded to other cities *(so no real connection between name & the whole operating area)*. and if you are a stranger who's on vacation or whatever, it can be impossible to find the correct service just by guessing names.

so how about **ordering the list** at least **by country, eventually by state (and so on)**, similar to how OsmAnd orders its list of downloadable maps?
the one thing i'm not 100% sure about is the search in this case... because it can be helpful to just search down the "folder" in which you currently are (instead of all, like now), but this has to be somehow clearly indicated.

speaking of OsmAnd: it would be **even better** to have (additionally) **a map** to chose the city/area/provider/service on which the operating area of the service is indicated *(similar to map areas in OsmAnd)* or at least marking its base *(as it is done at https://citybik.es/)* and it can be simply selected by a tap.
this (especially with indicating the operating area) would even better cover the case where the name doesn't really match the (whole) operating area.

**Comment by francoisfds** [comment]
Hi. Yeah I undestrand how annoying it is to search within a list of not enough accurate network names. Like you said, sort them by country is a good start ! Then, a map which points out each network location will be the must.

Regards.
