### ISSUE TITLE
Use all screen height on phones with rounded edges?

### ISSUE THREAD

**Issue by Altonss** [francoisfds/BikeSharingHub#37]
The bottom of the screen is black on phones with rounded edges, so we could utilise more screen space on these devices :)

**Comment by francoisfds** [comment]
Hello. I didn't notice there was a black area at the bottom until now, but there is ! It is very small but I believe that it is quite noticeable on smartphone with rounded edges. It seems that the issue don't appear on old Android versions like Android 5 for example, but it appears on recent Android.

Hopefully, I am currently migrating the app to targets Android 11 and it seems that the migration made this issue disapear (can't say how). So the fix will be in the next release if I'm right.

**Comment by Altonss** [comment]
> Hello. I didn't notice there was a black area at the bottom until now, but there is ! It is very small but I believe that it is quite noticeable on smartphone with rounded edges. It seems that the issue don't appear on old Android versions like Android 5 for example, but it appears on recent Android.
> 
> Hopefully, I am currently migrating the app to targets Android 11 and it seems that the migration made this issue disapear (can't say how). So the fix will be in the next release if I'm right.

On an Android 12 device the black area is pretty big, but I will wait for the next release and give further feedback :)

**Comment by Altonss** [comment]
It is fixed with the latest release, thanks!
