### ISSUE TITLE
Add to Play Store

### ISSUE THREAD

**Issue by theshininginception** [francoisfds/BikeSharingHub#43]
I think it would be nice to add it on Play Store so that the easier access to the app can attract more users.

**Comment by francoisfds** [comment]
Hello, yes I agree. Actualy that is planned for the next release 😉

**Comment by Altonss** [comment]
> Hello, yes I agree. Actualy that is planned for the next release wink

You mentionned this is planned for next release, and as 2.1.0 has just been released :heart_eyes: , is it still planned? Do you need some help? (I personnaly don't use Google Play, but if you think it's a nice to have, we could try it)

**Comment by francoisfds** [comment]
Yeah it is still plan, I've started the setup process this week but it takes more time than I thought (new graphical asset, juridic things). Thank you for your offer but it's quite ready ;) Then it will take time for them to review the app.

I don't use Google Play neither but I know that some phones don't allow to install APKs that are not in Google Play.

**Comment by francoisfds** [comment]
Yeah it is still plan, I've started the setup process this week but it takes more time than I thought (new graphical asset, juridic things). Thank you for your offer but it's quite ready ;) Then it will take time for them to review the app.

I don't use Google Play neither but I know that some phones don't allow to install APKs that are not in Google Play.

**Comment by francoisfds** [comment]
Yeah it is still plan, I've started the setup process this week but it takes more time than I thought (new graphical asset, juridic things). Thank you for your offer but it's quite ready ;) Then it will take time for them to review the app.

I don't use Google Play neither but I know that some phones don't allow to install APKs that are not in Google Play.

**Comment by francoisfds** [comment]
For your information the deployment request has been submitted to the store. Next step is the review from Google.

**Comment by francoisfds** [comment]
Hello. The app has been released today ! Now it is on both F-Droid and Google Play :+1: 
I will close this issue, but feel free to add any comment :wink:
