### ISSUE TITLE
Visual issue in network list

### ISSUE THREAD

**Issue by Altonss** [francoisfds/BikeSharingHub#44]
When searching for "Santa Marg" for example, you can find a network which information is partly hidden because the text is too long. This creates a "visual bug" which should/could maybe be handled better :)

**Comment by francoisfds** [comment]
Thank your for your comment, now it is fixed :wink:

**Comment by Altonss** [comment]
> Thank your for your comment, now it is fixed wink

Thanks a lot for the quick fix ;)
