### ISSUE TITLE
Display problem of favorites (scrolling)

### ISSUE THREAD

**Issue by Altonss** [francoisfds/BikeSharingHub#5]
With 9 favorites, just one more than the screen accepts without having to scroll). Issues:
- The last favorite (at the bottom of the list) is half masked by the last update info. I cannot scroll more up.
- When I want to scroll back to the top, it is nearly impossible because it triggers the refresh.

**Screenshot**
![Screenshot_2021-10-27-19-42-55](https://user-images.githubusercontent.com/66519591/139118419-b7d47fe5-b2fc-4e20-8947-fd9f0ab9ae8f.png)

**Hardware info:**
- Android 5.0.1
- Small screen size
- Version 2.0.4 from F-Droid

**Comment by Altonss** [comment]
Will this https://github.com/francoisfds/BikeSharingHub/commit/fb51fe90e98e4ef10a873e72f87e41fafbfc3612 commit also fix the view for the all stations tab?
And do you know if you are going to trigger a new release soon with this bugfix?

**Comment by francoisfds** [comment]
Hi Altonss, indeed it will fix the view for all tabs ;)
Actually I have some work in progress on the app which I plan to commit before triggerring a release, that's why !

**Comment by Altonss** [comment]
That's great !! I can't wait to see the new changes, what will it be about (if it's possible to tease lol)?

**Comment by francoisfds** [comment]
These changes will allow to select multiple bikesharing systems at the same time. It's an improvement which is already discussed in #3.

**Comment by francoisfds** [comment]
Hi,
Finally the new release is alive (v2.0.5). It will be available on F-Droid within the next days, otherwise there is a prebuilt in the repo's release section.

You will tell me, I think the scrolling problem is fixed :wink:

**Comment by Altonss** [comment]
Thanks a lot for the new release!
Once it is out on F-Droid I will test is :)

**Comment by Altonss** [comment]
This problem is not fixed, thanks!
