### ISSUE TITLE
Widget is showing parking spots for networks not having such info

### ISSUE THREAD

**Issue by Altonss** [francoisfds/BikeSharingHub#51]
For networks such as "LeVélo, Marseille", the widget is not behaving the same as inside the app and is displaying -1 parking spots despite this info being completely hidden inside the app (icon included) because this information isn't provided.
This could be improved for consistency :)

**Comment by francoisfds** [comment]
Hello @Altonss

Yes I agree this could be improved in the next release ! Thanks for reporting 😉

**Comment by francoisfds** [comment]
Hello @Altonss

Yes I agree this could be improved in the next release ! Thanks for reporting 😉

**Comment by francoisfds** [comment]
Hi, since version 2.1.1, the station's empty slots are not displayed anymore in the widget if the value is "-1" (means the info is not available). I close the issue 😉

**Comment by Altonss** [comment]
Thanks for the fix!
