### ISSUE TITLE
Widget is not handling several networks

### ISSUE THREAD

**Issue by Altonss** [francoisfds/BikeSharingHub#52]
Widget doesn't handle several networks selected:
- when initialising widget, info for only 1 network is showed
- when going to the app, the prefered stations are now only showing for 1 network until refresh!
- when going back to the widget, the prefered stations of the 2 networks are displayed correctly
- a refresh of the widget resets all to zero (information for only 1 network)

**Comment by francoisfds** [comment]
Hi. Indeed I just figured out that the source code requesting citybik.es is duplicated twice : inside the main view and inside the widget. The support for multiple networks was added only once, so the widget uses the old code (which overrites the embedded list of stations). I think we need to streamline the code in a single Service to avoid reporting every modification twice.

**Comment by francoisfds** [comment]
Since version 2.1.1, the widget is refreshing all the networks that are monitored. I close the issue 😉

**Comment by Altonss** [comment]
Thanks! It works great now :)
