### ISSUE TITLE
location-based features don't work

### ISSUE THREAD

**Issue by lmamane** [francoisfds/BikeSharingHub#53]
BikeSharingHub version 2.1.0 installed from F-Droid on LineageOS 20-20230124-NIGHTLY-lemonadep (Android 13). No Google services, but working GNSS-based location.

The app correctly shows my location on the map, which shows it has access to my location. Nevertheless:

- The "nearby" tab says "No nearby stations" even though I'm standing right at the station.
- Clicking on "circle with four prongs around a disc" icon (at the top right of the map) gives message "Location not found"

Note that while my location is correctly shown, it is very infrequently updated if I move while I leave the Map screen open; this gives me the impression that maybe BIkeSharingHub is able to access my location when the system knows it because another app has acquired it, but does not trigger the system into acquiring it?

![Screenshot_20230203-173224_BikeSharingHub](https://user-images.githubusercontent.com/7558692/216751033-cf61e3f2-9a9b-43d7-aff2-75f38be158d0.png)
![Screenshot_20230203-173234_BikeSharingHub](https://user-images.githubusercontent.com/7558692/216751031-78dfb03b-d8e3-4a50-b1ba-81dfbb00e224.png)
![Screenshot_20230203-173242_BikeSharingHub](https://user-images.githubusercontent.com/7558692/216751032-40ee81f3-fe39-42b2-834f-210285c918d1.png)
![Screenshot_20230203-173403_Permission controller](https://user-images.githubusercontent.com/7558692/216751029-fa47b8ce-3821-415a-a455-fff2f75ebccc.png)

**Comment by francoisfds** [comment]
Hello and thank you for spotting these issues !

Regarding the map, the location displayed is based on both GPS and network providers. Theroreticaly, the acquisition is done right when the map shows up, then it is updated only every 60 seconds or 1000 meters. But in case of GPS only, it will only work if the GPS fix is recent enough (as you said, if another app has triggered it recently).

Regarding the "nearby" tab and the "circle with four prongs around a disc" icon,  the location relies on the last known location managed by the "Network" provider only. In LineageOS, I think there is no Location Provider by default, and that would be the reason why it's not working right now.

Definitly this is a lack, so I will plan to add support for the GPS based location in BikeSharingHub. Also, I suppose that a button to refresh location on demand would be usefull.

**Comment by francoisfds** [comment]
Hello ! The release version 2.1.1 is available on F-Droid 👍
It improves the Nearby tab by using the last known GPS location (in addition to the previous behaviour). For the recall, the last known location is the one that have been computed the last time a GPS request has been made by any of the installed application (BikeSharingHub does a request only when you browse the Map). For the moment, there is no button to refresh location on demand (that said, browsing the map will do the trick).
Moreover, if the last known location is 10 minutes old, you will be warned by a message.

@lmamane please tell us if this release works well on LineageOS 😉

**Comment by lmamane** [comment]
Yes, 2.1.1 works well for me without Network location provider.
