### ISSUE TITLE
Improve translations like it is stlil done on OpenBikeSharing with weblate?

### ISSUE THREAD

**Issue by Altonss** [francoisfds/BikeSharingHub#9]
We still see translations being done in weblate for the openbikesharing project. Could BikeSharingHub also try to have some kind of translation done through weblate for example?

**Comment by francoisfds** [comment]
Hi, indeed this a must have feature to keep translations up to date and allow seamless contributions.

**Comment by francoisfds** [comment]
@Altonss do you know how to do set it up ?

**Comment by Altonss** [comment]
> @Altonss do you know how to do set it up ?

I am currently trying to set it up! But unfortunately don't have much time these days. When I have time to continue the work and if I need some help I will write a message here. The translation repo I am trying to set up is located here: https://hosted.weblate.org/projects/bikesharinghub/#information

**Comment by francoisfds** [comment]
OK, I have seen that, thank you very much ! Take the time you need 😉

**Comment by Altonss** [comment]
It looks like it is working now :+1: 
@francoisfds do you want write access to the weblate repo?

Things to be done:

- [ ] Set up repository links for an automated flow of updates to Weblate.
- [ ] Provide translation instructions to guide translators.
- [ ] Use flags to indicate special strings in your translation.
- [ ] The use of Weblate has been approved by the upstream project.
- [ ] Specify that you use Weblate for translations in the README. This will allow Weblate to become known, attract new translators and be used more widely (including by free projects).

**Comment by francoisfds** [comment]
Sure, I've just signed up there : https://hosted.weblate.org/user/francoisfds.
For the upstream project approval, is there something special to do ?

**Comment by Altonss** [comment]
> Sure, I've just signed up there : https://hosted.weblate.org/user/francoisfds. For the upstream project approval, is there something special to do ?

I have just added you as administrator and did a pr to add the weblate reference in the readme. The other points should not be showstopper right now. So if the PR gets merged, I will click on the button to ask for hosting :)

**Comment by francoisfds** [comment]
Great, the Readme is merged and new translations as well. Thank tou @Altonss.

**Comment by Altonss** [comment]
I really like this project, thank you for having revived the OpenBikeSharing app! I have just sent out the request for free hosting, will keep you informed of the progress :)

**Comment by Altonss** [comment]
The free hosting plan for our project has been accepted! I will now close the issue as all seem to work fine!
If something were to break, feel free to reopen this issue :)

**Comment by francoisfds** [comment]
Great, thanks a lot ! I have also set up automatic push from github to weblate so it can be kept up to update 👌

**Comment by Altonss** [comment]
> Great, thanks a lot ! I have also set up automatic push from github to weblate so it can be kept up to update ok_hand

I didn't know how to set this up, how did you do it?

**Comment by francoisfds** [comment]
I followed this guide : https://docs.weblate.org/fr/latest/admin/continuous.html#github-setup. It has to be set on github side so any new commit can trigger an update message. This needs admin rights on the repo I think.
Also, there was some features to explore on weblate to complete the trial plan : flags and screenshots. I'm not sure if it was mandatory.

**Comment by Altonss** [comment]
Have you changed some settings on weblate?
Because now some error is hapenning when pushing changes to github:
![image](https://user-images.githubusercontent.com/66519591/151215111-ad21558b-2689-4f2d-9c54-1f50d432340c.png)

**Comment by francoisfds** [comment]
Nothing on my side since last saturday, unless merging your German translation. That's strange !

**Comment by Altonss** [comment]
I don't really know :( I will have a look at it tomorrow :)

**Comment by francoisfds** [comment]
The error is not thrown for every change : https://hosted.weblate.org/projects/bikesharinghub/bikesharinghub/#repository
But wow, "Your branch is ahead of 'origin/master' by 26 commits", we may need to squash them ?
![screenshot](https://user-images.githubusercontent.com/15369785/151255899-e9d9861e-3cfb-4ddb-af54-a2299a8ee561.png)

**Comment by Altonss** [comment]
I just installed a module which always squashes the commits before sending. After squashing it worked again, so I guess it's fine now :)

**Comment by francoisfds** [comment]
Indeed that's a good thing, well done !

**Comment by francoisfds** [comment]
I opened a merge request in fdroiddata to advertise the weblate link :wink:

**Comment by Altonss** [comment]
Great idea! (I see your pipeline has failed on fdroid)

**Comment by francoisfds** [comment]
Yes, there was an order to follow in the yml file, but now the pipeline passed.

**Comment by francoisfds** [comment]
Hi @Altonss. The last merged weblate commit added new lines in all languages with emty value like :
```xml
<string name="app_name" translatable="false"></string>
```
Unfortunately now if you run the app with an other language than English, there are blank spaces instead of the actual string. I think we need to revert these changes, but first do you know what was their purpose ?

**Comment by Altonss** [comment]
Oh I'm sorry this happenned :/
Did someone trigger this changes or was this some kind of automated weblate thing?

**Comment by francoisfds** [comment]
I don't really know I think that was part of the 26 commits that were stuck in the beginning of the week. May be that was one automatic commit per each language ?!

**Comment by Altonss** [comment]
That is really strange. Let's just drop these changes and after that update the changes on weblate to match this repo.
I will also change the settings to squash the commits per language, so it will be easier to monitor the incoming changes!

**Comment by francoisfds** [comment]
Ok that's good idea to squash only per language, thanks ! I will revert the changes and we will see if this thing will be triggered again.

**Comment by Altonss** [comment]
Wait I have maybe found something!! There is a module that deletes blank translations, should I install it to correct the errors?

**Comment by francoisfds** [comment]
It's Okay I pushed the fix to the master branch. For me too weblate UI is French everywhere, because I'm French :wink:
It's not really about blanks spaces but empty strings which were copied from the default "strings" file. I assume the gilty plugin is "Nettoyer les fichiers de traduction", it states :

> Mettre à jour tous les fichiers de traduction pour qu’ils correspondent au fichier mono-langue de base. 

I think this is a good feature but that must exclude the keys with `translatable="false"`.

**Comment by Altonss** [comment]
Ok than let's just uninstall that module, after that we will have to clean the merge conflict alert and than it will hopefully be the end of the problems :)

**Comment by francoisfds** [comment]
Ok we leave it uninstalled and if new strings are added we will see. How do you know it is swedish ?

**Comment by Altonss** [comment]
![image](https://user-images.githubusercontent.com/66519591/151715045-70256b16-5bb4-4571-882c-6e366323f6a4.png)

**Comment by francoisfds** [comment]
Right, I didn't see the big warnings ! Oh that must be related to my previous commit.

**Comment by francoisfds** [comment]
There is some instructions to follow to fix the conflict. I can do it unless you are already doing it ?

**Comment by Altonss** [comment]
Yes do it! I understand it's git behind all that, but I don't how how to it :laughing:

**Comment by francoisfds** [comment]
I will look at that in moments.

**Comment by francoisfds** [comment]
We are all good, I rebased my commit on top of weblate's branch. In the future I will try to check weblate before pushing strings.
